[project]
name = "attendance"
version = "0.1.0"
description = "FEM's Attendance microservice"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "fastapi[standard]>=0.121.2",
    "sqlalchemy>=2.0.44",
    "uvicorn>=0.38.0",
]
